
import { Geist, Geist_Mono,Manrope } from "next/font/google";
import "./globals.css";
import Header from "../components/header/header"
import Footer from "../components/footer/footer"
import {SearchProvider} from "../context/SearchContext"


export const metadata = {
  title: "Les petits plats",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

  return (
    <html lang="fr">
      <head>
        <link rel="stylesheet" 
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css"/>
      </head>
      <body >
        <SearchProvider>
          <Header />
          {children}
          <Footer />
        </SearchProvider>
      </body>
    </html>
  );
}
